// ══════════════════════════════════════════
//  VINBASE — Fichier de traductions
//  Langues : fr, en, de
// ══════════════════════════════════════════

const TRANSLATIONS = {

  fr: {
    // Navigation
    nav_mes_vins:     '🍾 Mes vins',
    nav_plan_cave:    '🗺️ Plan de cave',
    nav_dashboard:    '📊 Tableau de bord',
    nav_deconnexion:  'Déconnexion',

    // Index
    index_subtitle:   'Ma cave à vin personnelle',
    index_connexion:  'Connexion',
    index_inscription:'Inscription',
    index_email:      'Adresse e-mail',
    index_pwd:        'Mot de passe',
    index_prenom:     'Votre prénom',
    index_pwd_min:    '8 caractères minimum',
    index_btn_login:  'Accéder à Vinbase',
    index_btn_register:'Créer mon compte',
    index_creation:   'Création…',
    index_connexion_loading: 'Connexion…',
    index_err_fields: 'Merci de remplir tous les champs.',
    index_err_pwd:    'Le mot de passe doit faire au moins 8 caractères.',
    index_err_login:  'Email ou mot de passe incorrect.',
    index_ok_register:'✅ Compte créé ! Vérifiez votre e-mail pour confirmer votre inscription.',

    // Cave — Toolbar
    cave_search_placeholder: 'Rechercher un vin, château, région…',
    cave_filter_all_colors:  'Toutes les couleurs',
    cave_sort_nom:       'Trier par nom',
    cave_sort_millesime: 'Trier par millésime',
    cave_sort_quantite:  'Trier par quantité',
    cave_sort_prix:      'Trier par prix',
    cave_btn_import:     '⬆ Importer',
    cave_btn_add:        '+ Ajouter',

    // Cave — Stats
    stat_total:     'Bouteilles au total',
    stat_rouge:     'Vins rouges',
    stat_blanc:     'Vins blancs',
    stat_rose_autre:'Rosés & autres',

    // Cave — Couleurs
    couleur_rouge:     'Rouge',
    couleur_blanc:     'Blanc',
    couleur_rose:      'Rosé',
    couleur_petillant: 'Pétillant',
    couleur_autre:     'Autre',

    // Cave — Vue tableau
    col_couleur:    'Couleur',
    col_nom:        'Nom / Château',
    col_millesime:  'Millésime',
    col_region:     'Région',
    col_qte:        'Qté',
    col_prix:       'Prix',
    col_maturite:   'Maturité',
    col_contenance: 'Cont.',
    col_actions:    'Actions',

    // Cave — Empty state
    cave_empty_title: 'Votre cave est vide',
    cave_empty_text:  'Commencez par ajouter votre première bouteille.',
    cave_no_result:   'Aucun résultat',
    cave_no_result_text: 'Essayez d\'autres mots-clés ou filtres.',

    // Cave — Formulaire ajout/édition
    form_add_title:   'Ajouter une bouteille',
    form_edit_title:  'Modifier la bouteille',
    form_ia_label:    '✨ Recherche intelligente par Claude IA',
    form_ia_placeholder: 'Ex : Château Margaux 2015, Barolo Gaja, Gevrey-Chambertin…',
    form_ia_hint:     'Tapez le nom d\'un vin — Claude proposera des suggestions automatiquement',
    form_photo_label: '📷 Photo de l\'étiquette',
    form_photo_camera:'📸 Appareil photo',
    form_photo_gallery:'🖼️ Galerie',
    form_photo_choose:'Cliquer pour choisir',
    form_photo_size:  'JPG, PNG — max 10 Mo',
    form_photo_ia_btn:'🔍 Identifier ce vin avec Claude IA',
    form_sep_ident:   'Identification',
    form_sep_cave:    'Cave & Valeur',
    form_sep_maturite:'Maturité & Accords',
    form_sep_photo:   'Photo de l\'étiquette',
    form_nom:         'Nom du vin *',
    form_chateau:     'Château / Domaine',
    form_couleur:     'Couleur *',
    form_couleur_choose: '— choisir —',
    form_millesime:   'Millésime',
    form_region:      'Région',
    form_appellation: 'Appellation',
    form_quantite:    'Quantité en cave',
    form_contenance:  'Contenance',
    form_prix:        'Prix d\'achat (CHF / €)',
    form_maturite_debut: 'À boire à partir de',
    form_maturite_fin:   'À boire jusqu\'en',
    form_plats:       'Accords mets & plats',
    form_note:        'Notes personnelles',
    form_plats_placeholder: 'ex : Agneau, gibier, fromages affinés',
    form_note_placeholder:  'Robe, nez, bouche, impressions…',
    form_btn_cancel:  'Annuler',
    form_btn_save:    'Enregistrer',
    form_btn_saving:  'Enregistrement…',
    form_err_nom:     'Le nom du vin est obligatoire.',
    form_err_couleur: 'Veuillez choisir une couleur.',

    // Cave — Maturité badges
    mat_trop_jeune: '⏳ Trop jeune',
    mat_maturite:   '✅ En maturité',
    mat_apogee:     '🌟 Apogée',
    mat_declin:     '⚠️ En déclin',

    // Cave — Import
    import_title:     'Importer des bouteilles',
    import_step1:     'Étape 1 — Télécharger le modèle',
    import_step1_text:'Remplis ce fichier CSV avec tes vins, puis importe-le ci-dessous.',
    import_dl_btn:    '⬇ Télécharger le modèle CSV',
    import_cols:      'Colonnes reconnues',
    import_warning:   '⚠️ La colonne nom et couleur sont obligatoires.',
    import_step2:     'Étape 2 — Importer ton fichier',
    import_drop:      'Glisse ton fichier ici ou clique pour choisir',
    import_formats:   'CSV ou Excel (.csv, .xlsx, .xls)',
    import_preview:   'Aperçu',
    import_btn:       'Importer les bouteilles',
    import_btn_cancel:'Annuler',

    // Cave — Détail
    detail_nom:       'Nom',
    detail_chateau:   'Château / Domaine',
    detail_couleur:   'Couleur',
    detail_millesime: 'Millésime',
    detail_region:    'Région',
    detail_appellation:'Appellation',
    detail_quantite:  'Quantité',
    detail_contenance:'Contenance',
    detail_prix:      'Prix d\'achat',
    detail_maturite:  'Fenêtre de maturité',
    detail_accords:   'Accords mets',
    detail_notes:     'Notes personnelles',
    detail_btn_close: 'Fermer',
    detail_btn_edit:  'Modifier',

    // Cave — Suppressions
    confirm_delete:   'Supprimer "{nom}" de votre cave ?',

    // Dashboard
    dash_title:       'Tableau de bord',
    dash_updated:     'Mise à jour le',
    dash_valeur:      'Valeur de ma cave',
    dash_prix_total:  'Prix d\'achat total',
    dash_bouteilles:  'Bouteilles',
    dash_references:  'Références',
    dash_prix_moyen:  'Prix moyen',
    dash_par_couleur: 'Par couleur',
    dash_phases:      'Phases de maturité',
    dash_trop_jeune:  '⏳ Trop jeune',
    dash_en_maturite: '✅ En maturité',
    dash_apogee:      '🌟 À l\'apogée',
    dash_declin:      '⚠️ En déclin',
    dash_sans_info:   'bouteille(s) sans information de maturité',
    dash_valeur_couleur: 'Valeur par couleur',
    dash_regions:     'Répartition par région',
    dash_timeline:    'Fenêtre de dégustation',
    dash_etat:        'État des bouteilles',
    dash_bientot:     'À boire cette année et l\'année prochaine',
    dash_depasse:     '⚠️ Bouteilles dépassées ou à consommer vite',
    dash_entrees:     'Dernières bouteilles ajoutées',
    dash_cave_vide:   'Votre cave est vide.',
    dash_ajouter_lien:'Ajoutez vos premières bouteilles',
    dash_no_prix:     'Aucun prix renseigné',
    dash_no_region:   'Aucune région renseignée',
    dash_no_maturite: 'Aucune information de maturité renseignée',
    dash_no_bientot:  'Aucun vin à boire cette année ou l\'année prochaine',
    dash_no_depasse:  '✅ Aucune bouteille dépassée',
    dash_btl:         'btl',
    dash_col_vin:     'Vin',
    dash_col_millesime:'Millésime',
    dash_col_qte:     'Qté',
    dash_col_etat:    'État',
    dash_col_maturite:'Maturité',
    dash_col_accords: 'Accords',
    dash_col_fin:     'Jusqu\'en',
    dash_col_fin_mat: 'Fin maturité',
    dash_col_chateau: 'Château / Domaine',
    dash_col_couleur: 'Couleur',
    dash_col_region:  'Région',
    dash_col_prix:    'Prix unitaire',
    dash_col_ajoute:  'Ajouté le',
    dash_depuis:      'Depuis',
    dash_an:          'an',

    // Plan de cave
    plan_title:       'Plan de cave',
    plan_add_meuble:  '+ Ajouter un meuble',
    plan_legende:     'Légende',
    plan_vide:        'Vide',
    plan_hint:        '💡 Clique sur une case pour placer ou déplacer une bouteille',
    plan_empty_title: 'Aucun meuble créé',
    plan_empty_text:  'Commencez par créer votre premier meuble ou casier.',
    plan_modal_new:   'Nouveau meuble',
    plan_modal_edit:  'Modifier le meuble',
    plan_nom_label:   'Nom du meuble *',
    plan_nom_ph:      'ex : Casier principal, Armoire à vin, Cave nord…',
    plan_colonnes:    'Colonnes *',
    plan_rangees:     'Rangées *',
    plan_capacite:    'Capacité :',
    plan_capacite_unit:'bouteilles',
    plan_btn_create:  'Créer le meuble',
    plan_btn_cancel:  'Annuler',
    plan_btn_modify:  '✏️ Modifier',
    plan_col:         'col.',
    plan_rng:         'rng.',
    plan_emplacements:'emplacements',
    plan_occupe:      'Occupé :',
    plan_libre:       'Libre :',
    plan_taux:        'Taux :',
    plan_choisir_titre:'Placer une bouteille',
    plan_search_ph:   '🔍 Rechercher un vin…',
    plan_aucun_vin:   'Aucun vin trouvé',
    plan_detail_titre:'Bouteille',
    plan_btn_retirer: '🗑 Retirer de la case',
    plan_btn_deplacer:'↔ Déplacer',
    plan_btn_fermer:  'Fermer',
    plan_btn_close:   'Annuler',
    plan_emplacement: 'Emplacement',
    plan_confirm_del: 'Supprimer le meuble "{nom}" et tous ses emplacements ?',
    plan_deplacer_msg:'Clique maintenant sur la case de destination pour y déplacer la bouteille.',
    plan_emplacement_label: 'Emplacement : colonne',
    plan_rangee_label:'rangée',
  },

  en: {
    nav_mes_vins:     '🍾 My wines',
    nav_plan_cave:    '🗺️ Cellar map',
    nav_dashboard:    '📊 Dashboard',
    nav_deconnexion:  'Sign out',

    index_subtitle:   'My personal wine cellar',
    index_connexion:  'Sign in',
    index_inscription:'Register',
    index_email:      'Email address',
    index_pwd:        'Password',
    index_prenom:     'Your first name',
    index_pwd_min:    'Minimum 8 characters',
    index_btn_login:  'Access Vinbase',
    index_btn_register:'Create my account',
    index_creation:   'Creating…',
    index_connexion_loading: 'Signing in…',
    index_err_fields: 'Please fill in all fields.',
    index_err_pwd:    'Password must be at least 8 characters.',
    index_err_login:  'Incorrect email or password.',
    index_ok_register:'✅ Account created! Check your email to confirm your registration.',

    cave_search_placeholder: 'Search wine, château, region…',
    cave_filter_all_colors:  'All colors',
    cave_sort_nom:       'Sort by name',
    cave_sort_millesime: 'Sort by vintage',
    cave_sort_quantite:  'Sort by quantity',
    cave_sort_prix:      'Sort by price',
    cave_btn_import:     '⬆ Import',
    cave_btn_add:        '+ Add',

    stat_total:     'Total bottles',
    stat_rouge:     'Red wines',
    stat_blanc:     'White wines',
    stat_rose_autre:'Rosés & others',

    couleur_rouge:     'Red',
    couleur_blanc:     'White',
    couleur_rose:      'Rosé',
    couleur_petillant: 'Sparkling',
    couleur_autre:     'Other',

    col_couleur:    'Color',
    col_nom:        'Name / Château',
    col_millesime:  'Vintage',
    col_region:     'Region',
    col_qte:        'Qty',
    col_prix:       'Price',
    col_maturite:   'Maturity',
    col_contenance: 'Size',
    col_actions:    'Actions',

    cave_empty_title: 'Your cellar is empty',
    cave_empty_text:  'Start by adding your first bottle.',
    cave_no_result:   'No results',
    cave_no_result_text: 'Try other keywords or filters.',

    form_add_title:   'Add a bottle',
    form_edit_title:  'Edit bottle',
    form_ia_label:    '✨ Intelligent search by Claude AI',
    form_ia_placeholder: 'E.g.: Château Margaux 2015, Barolo Gaja…',
    form_ia_hint:     'Type a wine name — Claude will suggest matches automatically',
    form_photo_label: '📷 Label photo',
    form_photo_camera:'📸 Camera',
    form_photo_gallery:'🖼️ Gallery',
    form_photo_choose:'Click to choose',
    form_photo_size:  'JPG, PNG — max 10 MB',
    form_photo_ia_btn:'🔍 Identify this wine with Claude AI',
    form_sep_ident:   'Identification',
    form_sep_cave:    'Cellar & Value',
    form_sep_maturite:'Maturity & Pairings',
    form_sep_photo:   'Label photo',
    form_nom:         'Wine name *',
    form_chateau:     'Château / Estate',
    form_couleur:     'Color *',
    form_couleur_choose: '— choose —',
    form_millesime:   'Vintage',
    form_region:      'Region',
    form_appellation: 'Appellation',
    form_quantite:    'Quantity in cellar',
    form_contenance:  'Bottle size',
    form_prix:        'Purchase price (CHF / €)',
    form_maturite_debut: 'Drink from',
    form_maturite_fin:   'Drink until',
    form_plats:       'Food pairings',
    form_note:        'Personal notes',
    form_plats_placeholder: 'e.g.: Lamb, game, aged cheese',
    form_note_placeholder:  'Color, nose, palate, impressions…',
    form_btn_cancel:  'Cancel',
    form_btn_save:    'Save',
    form_btn_saving:  'Saving…',
    form_err_nom:     'Wine name is required.',
    form_err_couleur: 'Please choose a color.',

    mat_trop_jeune: '⏳ Too young',
    mat_maturite:   '✅ At peak',
    mat_apogee:     '🌟 Apogee',
    mat_declin:     '⚠️ Declining',

    import_title:     'Import bottles',
    import_step1:     'Step 1 — Download the template',
    import_step1_text:'Fill this CSV file with your wines, then import it below.',
    import_dl_btn:    '⬇ Download CSV template',
    import_cols:      'Recognized columns',
    import_warning:   '⚠️ The name and color columns are required.',
    import_step2:     'Step 2 — Import your file',
    import_drop:      'Drop your file here or click to choose',
    import_formats:   'CSV or Excel (.csv, .xlsx, .xls)',
    import_preview:   'Preview',
    import_btn:       'Import bottles',
    import_btn_cancel:'Cancel',

    detail_nom:       'Name',
    detail_chateau:   'Château / Estate',
    detail_couleur:   'Color',
    detail_millesime: 'Vintage',
    detail_region:    'Region',
    detail_appellation:'Appellation',
    detail_quantite:  'Quantity',
    detail_contenance:'Bottle size',
    detail_prix:      'Purchase price',
    detail_maturite:  'Drinking window',
    detail_accords:   'Food pairings',
    detail_notes:     'Personal notes',
    detail_btn_close: 'Close',
    detail_btn_edit:  'Edit',

    confirm_delete:   'Remove "{nom}" from your cellar?',

    dash_title:       'Dashboard',
    dash_updated:     'Updated on',
    dash_valeur:      'Cellar value',
    dash_prix_total:  'Total purchase price',
    dash_bouteilles:  'Bottles',
    dash_references:  'References',
    dash_prix_moyen:  'Average price',
    dash_par_couleur: 'By color',
    dash_phases:      'Maturity phases',
    dash_trop_jeune:  '⏳ Too young',
    dash_en_maturite: '✅ At peak',
    dash_apogee:      '🌟 Apogee',
    dash_declin:      '⚠️ Declining',
    dash_sans_info:   'bottle(s) with no maturity info',
    dash_valeur_couleur: 'Value by color',
    dash_regions:     'By region',
    dash_timeline:    'Drinking window',
    dash_etat:        'Bottle status',
    dash_bientot:     'Drink this year or next',
    dash_depasse:     '⚠️ Past peak or drink soon',
    dash_entrees:     'Latest additions',
    dash_cave_vide:   'Your cellar is empty.',
    dash_ajouter_lien:'Add your first bottles',
    dash_no_prix:     'No prices entered',
    dash_no_region:   'No regions entered',
    dash_no_maturite: 'No maturity information entered',
    dash_no_bientot:  'No wines to drink this year or next',
    dash_no_depasse:  '✅ No bottles past peak',
    dash_btl:         'btl',
    dash_col_vin:     'Wine',
    dash_col_millesime:'Vintage',
    dash_col_qte:     'Qty',
    dash_col_etat:    'Status',
    dash_col_maturite:'Maturity',
    dash_col_accords: 'Pairings',
    dash_col_fin:     'Until',
    dash_col_fin_mat: 'Peak end',
    dash_col_chateau: 'Château / Estate',
    dash_col_couleur: 'Color',
    dash_col_region:  'Region',
    dash_col_prix:    'Unit price',
    dash_col_ajoute:  'Added on',
    dash_depuis:      'Since',
    dash_an:          'yr',

    plan_title:       'Cellar map',
    plan_add_meuble:  '+ Add a unit',
    plan_legende:     'Legend',
    plan_vide:        'Empty',
    plan_hint:        '💡 Click a slot to place or move a bottle',
    plan_empty_title: 'No storage unit created',
    plan_empty_text:  'Start by creating your first rack or cabinet.',
    plan_modal_new:   'New storage unit',
    plan_modal_edit:  'Edit storage unit',
    plan_nom_label:   'Unit name *',
    plan_nom_ph:      'e.g.: Main rack, Wine cabinet, North cellar…',
    plan_colonnes:    'Columns *',
    plan_rangees:     'Rows *',
    plan_capacite:    'Capacity:',
    plan_capacite_unit:'bottles',
    plan_btn_create:  'Create unit',
    plan_btn_cancel:  'Cancel',
    plan_btn_modify:  '✏️ Edit',
    plan_col:         'col.',
    plan_rng:         'row',
    plan_emplacements:'slots',
    plan_occupe:      'Used:',
    plan_libre:       'Free:',
    plan_taux:        'Rate:',
    plan_choisir_titre:'Place a bottle',
    plan_search_ph:   '🔍 Search a wine…',
    plan_aucun_vin:   'No wine found',
    plan_detail_titre:'Bottle',
    plan_btn_retirer: '🗑 Remove from slot',
    plan_btn_deplacer:'↔ Move',
    plan_btn_fermer:  'Close',
    plan_btn_close:   'Cancel',
    plan_emplacement: 'Slot',
    plan_confirm_del: 'Delete unit "{nom}" and all its slots?',
    plan_deplacer_msg:'Now click the destination slot to move the bottle.',
    plan_emplacement_label: 'Slot: column',
    plan_rangee_label:'row',
  },

  de: {
    nav_mes_vins:     '🍾 Meine Weine',
    nav_plan_cave:    '🗺️ Kellerplan',
    nav_dashboard:    '📊 Dashboard',
    nav_deconnexion:  'Abmelden',

    index_subtitle:   'Mein persönlicher Weinkeller',
    index_connexion:  'Anmelden',
    index_inscription:'Registrieren',
    index_email:      'E-Mail-Adresse',
    index_pwd:        'Passwort',
    index_prenom:     'Ihr Vorname',
    index_pwd_min:    'Mindestens 8 Zeichen',
    index_btn_login:  'Zugang zu Vinbase',
    index_btn_register:'Konto erstellen',
    index_creation:   'Wird erstellt…',
    index_connexion_loading: 'Anmeldung…',
    index_err_fields: 'Bitte füllen Sie alle Felder aus.',
    index_err_pwd:    'Das Passwort muss mindestens 8 Zeichen lang sein.',
    index_err_login:  'Falsche E-Mail oder falsches Passwort.',
    index_ok_register:'✅ Konto erstellt! Prüfen Sie Ihre E-Mail zur Bestätigung.',

    cave_search_placeholder: 'Wein, Château, Region suchen…',
    cave_filter_all_colors:  'Alle Farben',
    cave_sort_nom:       'Nach Name sortieren',
    cave_sort_millesime: 'Nach Jahrgang sortieren',
    cave_sort_quantite:  'Nach Menge sortieren',
    cave_sort_prix:      'Nach Preis sortieren',
    cave_btn_import:     '⬆ Importieren',
    cave_btn_add:        '+ Hinzufügen',

    stat_total:     'Flaschen gesamt',
    stat_rouge:     'Rotweine',
    stat_blanc:     'Weissweine',
    stat_rose_autre:'Rosé & andere',

    couleur_rouge:     'Rot',
    couleur_blanc:     'Weiss',
    couleur_rose:      'Rosé',
    couleur_petillant: 'Schaumwein',
    couleur_autre:     'Andere',

    col_couleur:    'Farbe',
    col_nom:        'Name / Château',
    col_millesime:  'Jahrgang',
    col_region:     'Region',
    col_qte:        'Mge',
    col_prix:       'Preis',
    col_maturite:   'Reife',
    col_contenance: 'Grösse',
    col_actions:    'Aktionen',

    cave_empty_title: 'Ihr Keller ist leer',
    cave_empty_text:  'Fügen Sie Ihre erste Flasche hinzu.',
    cave_no_result:   'Keine Ergebnisse',
    cave_no_result_text: 'Versuchen Sie andere Suchbegriffe.',

    form_add_title:   'Flasche hinzufügen',
    form_edit_title:  'Flasche bearbeiten',
    form_ia_label:    '✨ Intelligente Suche mit Claude KI',
    form_ia_placeholder: 'z.B.: Château Margaux 2015, Barolo Gaja…',
    form_ia_hint:     'Weinnamen eingeben — Claude schlägt automatisch vor',
    form_photo_label: '📷 Etikett-Foto',
    form_photo_camera:'📸 Kamera',
    form_photo_gallery:'🖼️ Galerie',
    form_photo_choose:'Klicken zum Auswählen',
    form_photo_size:  'JPG, PNG — max. 10 MB',
    form_photo_ia_btn:'🔍 Wein mit Claude KI identifizieren',
    form_sep_ident:   'Identifikation',
    form_sep_cave:    'Keller & Wert',
    form_sep_maturite:'Reife & Speisebegleitung',
    form_sep_photo:   'Etikett-Foto',
    form_nom:         'Weinname *',
    form_chateau:     'Château / Weingut',
    form_couleur:     'Farbe *',
    form_couleur_choose: '— auswählen —',
    form_millesime:   'Jahrgang',
    form_region:      'Region',
    form_appellation: 'Appellation',
    form_quantite:    'Menge im Keller',
    form_contenance:  'Flaschengrösse',
    form_prix:        'Kaufpreis (CHF / €)',
    form_maturite_debut: 'Trinken ab',
    form_maturite_fin:   'Trinken bis',
    form_plats:       'Speisebegleitung',
    form_note:        'Persönliche Notizen',
    form_plats_placeholder: 'z.B.: Lamm, Wild, gereifter Käse',
    form_note_placeholder:  'Farbe, Nase, Gaumen, Eindrücke…',
    form_btn_cancel:  'Abbrechen',
    form_btn_save:    'Speichern',
    form_btn_saving:  'Wird gespeichert…',
    form_err_nom:     'Der Weinname ist erforderlich.',
    form_err_couleur: 'Bitte wählen Sie eine Farbe.',

    mat_trop_jeune: '⏳ Zu jung',
    mat_maturite:   '✅ Trinkreif',
    mat_apogee:     '🌟 Höhepunkt',
    mat_declin:     '⚠️ Im Abstieg',

    import_title:     'Flaschen importieren',
    import_step1:     'Schritt 1 — Vorlage herunterladen',
    import_step1_text:'Füllen Sie diese CSV-Datei mit Ihren Weinen aus.',
    import_dl_btn:    '⬇ CSV-Vorlage herunterladen',
    import_cols:      'Erkannte Spalten',
    import_warning:   '⚠️ Name und Farbe sind Pflichtfelder.',
    import_step2:     'Schritt 2 — Datei importieren',
    import_drop:      'Datei hierher ziehen oder klicken',
    import_formats:   'CSV oder Excel (.csv, .xlsx, .xls)',
    import_preview:   'Vorschau',
    import_btn:       'Flaschen importieren',
    import_btn_cancel:'Abbrechen',

    detail_nom:       'Name',
    detail_chateau:   'Château / Weingut',
    detail_couleur:   'Farbe',
    detail_millesime: 'Jahrgang',
    detail_region:    'Region',
    detail_appellation:'Appellation',
    detail_quantite:  'Menge',
    detail_contenance:'Flaschengrösse',
    detail_prix:      'Kaufpreis',
    detail_maturite:  'Trinkreife-Fenster',
    detail_accords:   'Speisebegleitung',
    detail_notes:     'Persönliche Notizen',
    detail_btn_close: 'Schliessen',
    detail_btn_edit:  'Bearbeiten',

    confirm_delete:   '"{nom}" aus Ihrem Keller entfernen?',

    dash_title:       'Dashboard',
    dash_updated:     'Aktualisiert am',
    dash_valeur:      'Kellerwert',
    dash_prix_total:  'Gesamtkaufpreis',
    dash_bouteilles:  'Flaschen',
    dash_references:  'Referenzen',
    dash_prix_moyen:  'Durchschnittspreis',
    dash_par_couleur: 'Nach Farbe',
    dash_phases:      'Reifephasen',
    dash_trop_jeune:  '⏳ Zu jung',
    dash_en_maturite: '✅ Trinkreif',
    dash_apogee:      '🌟 Höhepunkt',
    dash_declin:      '⚠️ Im Abstieg',
    dash_sans_info:   'Flasche(n) ohne Reifeinformation',
    dash_valeur_couleur: 'Wert nach Farbe',
    dash_regions:     'Nach Region',
    dash_timeline:    'Trinkreife-Fenster',
    dash_etat:        'Flaschenstatus',
    dash_bientot:     'Dieses oder nächstes Jahr trinken',
    dash_depasse:     '⚠️ Überschrittener Höhepunkt',
    dash_entrees:     'Zuletzt hinzugefügt',
    dash_cave_vide:   'Ihr Keller ist leer.',
    dash_ajouter_lien:'Erste Flaschen hinzufügen',
    dash_no_prix:     'Keine Preise eingetragen',
    dash_no_region:   'Keine Regionen eingetragen',
    dash_no_maturite: 'Keine Reifeinformationen eingetragen',
    dash_no_bientot:  'Kein Wein dieses oder nächstes Jahr zu trinken',
    dash_no_depasse:  '✅ Keine Flaschen über dem Höhepunkt',
    dash_btl:         'Fl.',
    dash_col_vin:     'Wein',
    dash_col_millesime:'Jahrgang',
    dash_col_qte:     'Mge',
    dash_col_etat:    'Status',
    dash_col_maturite:'Reife',
    dash_col_accords: 'Speisen',
    dash_col_fin:     'Bis',
    dash_col_fin_mat: 'Reife-Ende',
    dash_col_chateau: 'Château / Weingut',
    dash_col_couleur: 'Farbe',
    dash_col_region:  'Region',
    dash_col_prix:    'Einzelpreis',
    dash_col_ajoute:  'Hinzugefügt am',
    dash_depuis:      'Seit',
    dash_an:          'J.',

    plan_title:       'Kellerplan',
    plan_add_meuble:  '+ Möbel hinzufügen',
    plan_legende:     'Legende',
    plan_vide:        'Leer',
    plan_hint:        '💡 Klicken Sie auf ein Fach zum Platzieren oder Verschieben',
    plan_empty_title: 'Kein Möbel erstellt',
    plan_empty_text:  'Erstellen Sie Ihr erstes Regal oder Weinschrank.',
    plan_modal_new:   'Neues Möbelstück',
    plan_modal_edit:  'Möbel bearbeiten',
    plan_nom_label:   'Möbelname *',
    plan_nom_ph:      'z.B.: Hauptregal, Weinschrank, Nordkeller…',
    plan_colonnes:    'Spalten *',
    plan_rangees:     'Reihen *',
    plan_capacite:    'Kapazität:',
    plan_capacite_unit:'Flaschen',
    plan_btn_create:  'Möbel erstellen',
    plan_btn_cancel:  'Abbrechen',
    plan_btn_modify:  '✏️ Bearbeiten',
    plan_col:         'Sp.',
    plan_rng:         'Re.',
    plan_emplacements:'Plätze',
    plan_occupe:      'Belegt:',
    plan_libre:       'Frei:',
    plan_taux:        'Quote:',
    plan_choisir_titre:'Flasche platzieren',
    plan_search_ph:   '🔍 Wein suchen…',
    plan_aucun_vin:   'Kein Wein gefunden',
    plan_detail_titre:'Flasche',
    plan_btn_retirer: '🗑 Aus dem Fach entfernen',
    plan_btn_deplacer:'↔ Verschieben',
    plan_btn_fermer:  'Schliessen',
    plan_btn_close:   'Abbrechen',
    plan_emplacement: 'Platz',
    plan_confirm_del: 'Möbel "{nom}" und alle Plätze löschen?',
    plan_deplacer_msg:'Klicken Sie nun auf den Zielplatz.',
    plan_emplacement_label: 'Platz: Spalte',
    plan_rangee_label:'Reihe',
  }
};

// ── Détection et gestion de la langue ──
function getLang() {
  const saved = localStorage.getItem('vinbase_lang');
  if (saved && TRANSLATIONS[saved]) return saved;
  const browser = navigator.language?.slice(0,2).toLowerCase();
  if (browser === 'de') return 'de';
  if (browser === 'en') return 'en';
  return 'fr';
}

function setLang(lang) {
  localStorage.setItem('vinbase_lang', lang);
  location.reload();
}

function t(key) {
  const lang = getLang();
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['fr']?.[key] || key;
}

// ── Injecter le sélecteur de langue dans le header ──
function injecterSelecteurLang() {
  const lang = getLang();
  const flags = { fr: '🇫🇷', en: '🇬🇧', de: '🇩🇪' };
  const wrap = document.createElement('div');
  wrap.style.cssText = 'display:flex;gap:0.25rem;align-items:center';
  ['fr','en','de'].forEach(l => {
    const btn = document.createElement('button');
    btn.textContent = flags[l];
    btn.title = l.toUpperCase();
    btn.style.cssText = `background:none;border:none;cursor:pointer;font-size:1.1rem;opacity:${lang===l?1:0.4};transition:opacity 0.2s;padding:0.2rem`;
    btn.addEventListener('click', () => setLang(l));
    btn.addEventListener('mouseenter', () => { if (lang !== l) btn.style.opacity = '0.8'; });
    btn.addEventListener('mouseleave', () => { if (lang !== l) btn.style.opacity = '0.4'; });
    wrap.appendChild(btn);
  });
  return wrap;
}
